#!/bin/bash

# export OCTOMON_OCTOPUS_ADDRESS=https://demo.octopusdeploy.com
# export OCTOMON_OCTOPUS_APIKEY=API-GUEST
export OCTOMON_OCTOPUS_ADDRESS=http://localhost:8888/
export OCTOMON_OCTOPUS_APIKEY=API-XXFXIJUGACOAAFSY70SGSDEIPEGSNRVL
go run main.go

